### ISSUE TITLE
Some of the sample notebooks are out of sync

### ISSUE THREAD

**Issue by jhenin** [BranniganLab/safep#14]
In my tests, only the BAR-estimator-basic works directly as expected out of the box. Other try to load the `AFEP_parse` module, which is not available after a `pip install`. Should this be replaced by importing the `safep` module? It's unclear to me if that covers all the functionality of `AFEP_parse`.

**Comment by EzryStIago** [comment]
Almost, I'm working on the update.

**Comment by jhenin** [comment]
Thanks @EzryStIago ! About specific needs: I think they will always require users to adapt the notebooks to their needs, so we need them to have the basic bricks and to be easy to tinker with, which I think is already the case to a large extent.

**Comment by EzryStIago** [comment]
The main notebooks are up to date.
